services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=orders_db"
      - "POSTGRES_USER=local"
      - "POSTGRES_PASSWORD=local"
    ports:
      - "5440:5432"
    networks:
      - eshop-orders-service-network

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: local
      RABBITMQ_DEFAULT_PASS: local
      RABBITMQ_DEFAULT_VHOST: / 
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - eshop-orders-service-network

  # keycloak:
  #   image: quay.io/keycloak/keycloak
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   ports:
  #     - 8443:8080
  #   command:
  #     - start-dev
  #   networks:
  #     - eshop-orders-service-network

  # wiremock:
  #   image: "wiremock/wiremock:latest"
  #   ports:
  #     - 127.0.0.1:8080:8080
  #   volumes:
  #     - ./wiremock/__files:/home/wiremock/__files
  #     - ./wiremock/mappings:/home/wiremock/mappings
  #   entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

networks:
  eshop-orders-service-network:
    name: eshop-orders-service-network
