persistence:
  order:
    readable-datasource: 
      url: jdbc:h2:mem:orders_readable;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    writable-datasource: 
      url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}

h2:
  url: jdbc:h2:mem:orders_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    tryItOutEnabled: true
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
    filter: true
openapi:
  dev-url: http://localhost:8080
  prod-url: http://localhost:8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eshop-orders-service
  flyway:
    enabled: true
  cache:
    type: redis
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orders_readable_db
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: ${persistence.order.writable-datasource}
    username: ${postgres.username}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: local
    password: local
    virtual-host: /
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: '3'
          initial-interval: 2s
          multiplier: '2'
