persistence:
  order:
    readable-datasource: 
      url: jdbc:h2:mem:orders_readable;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    writable-datasource: 
      url: jdbc:h2:mem:orders_writable;MODE=MYSQL;DATABASE_TO_LOWER=TRUE

h2:
  url: jdbc:h2:mem:orders_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE

spring:
  datasource:
    url: ${h2.url}
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: eshop-orders-service
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: local
    password: local
    virtual-host: /